version: "3.7"

services:
  surf:
    image: uncwlibrary/surf
    container_name: surf
    labels:
      - traefik.enable=true
      - traefik.http.routers.surf.entrypoints=websecure
      - traefik.http.routers.surf.rule=Host(`library.uncw.edu`) && PathPrefix(`/surf`)
      - traefik.http.routers.surf.tls=true
      - traefik.http.routers.surf.priority=999
      - traefik.http.services.surf.loadbalancer.server.port=80
    restart: unless-stopped

networks:
  default:
    name: traefik_net
    external: true
